# Generated by Django 4.2.2 on 2023-06-23 20:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('event_name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=30, unique=True)),
                ('tg_nickname', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator(message='Invalid Email')])),
                ('full_name', models.CharField(blank=True, max_length=50)),
                ('workplace', models.CharField(blank=True, max_length=150)),
                ('experience', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('L', 'Listener'), ('S', 'Speaker'), ('O', 'Organizer')], default='L', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=50)),
                ('planed_start_time', models.TimeField()),
                ('planed_end_time', models.TimeField()),
                ('actual_start_time', models.TimeField(blank=True)),
                ('actual_end_time', models.TimeField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.event')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=150)),
                ('question_text', models.TextField(unique=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user')),
            ],
        ),
    ]
