# Generated by Django 4.2.2 on 2023-06-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_nickname',
            field=models.CharField(max_length=30),
        ),
    ]
