# Generated by Django 4.2.2 on 2023-06-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_user_tg_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='actual_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='actual_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
